"""
Base template class for Robot Framework code generation
"""

from abc import ABC, abstractmethod
from string import Template
from typing import Dict, Any, Optional
from datetime import datetime


class BaseTemplate(ABC):
    """Base class for all Robot Framework templates"""
    
    def __init__(self):
        self.generated_at = datetime.now().isoformat()
    
    @abstractmethod
    def generate(self, **kwargs) -> str:
        """Generate the Robot Framework code"""
        pass
    
    def _get_header(self, description: str = "") -> str:
        """Generate a standard header comment"""
        return f"""# Generated by Robot Framework MCP Server
# Date: {self.generated_at}
# Description: {description}
# ============================================

"""
    
    def _safe_substitute(self, template_str: str, **kwargs) -> str:
        """Safely substitute template variables"""
        template = Template(template_str)
        return template.safe_substitute(**kwargs)
    
    def _get_settings_section(
        self,
        libraries: list = None,
        resources: list = None,
        variables: list = None,
        suite_setup: str = None,
        suite_teardown: str = None,
        test_setup: str = None,
        test_teardown: str = None,
    ) -> str:
        """Generate Settings section"""
        lines = ["*** Settings ***"]
        
        if libraries:
            for lib in libraries:
                if isinstance(lib, tuple):
                    lines.append(f"Library    {lib[0]}    {lib[1]}")
                else:
                    lines.append(f"Library    {lib}")
        
        if resources:
            for res in resources:
                lines.append(f"Resource    {res}")
        
        if variables:
            for var in variables:
                lines.append(f"Variables    {var}")
        
        if suite_setup:
            lines.append(f"Suite Setup    {suite_setup}")
        if suite_teardown:
            lines.append(f"Suite Teardown    {suite_teardown}")
        if test_setup:
            lines.append(f"Test Setup    {test_setup}")
        if test_teardown:
            lines.append(f"Test Teardown    {test_teardown}")
        
        return '\n'.join(lines) + '\n'
    
    def _get_variables_section(self, variables: Dict[str, Any]) -> str:
        """Generate Variables section"""
        if not variables:
            return ""
        
        lines = ["*** Variables ***"]
        for name, value in variables.items():
            # Ensure proper variable naming
            if not name.startswith('${'):
                name = f"${{{name}}}"
            lines.append(f"{name}    {value}")
        
        return '\n'.join(lines) + '\n'
    
    def _format_keyword(
        self,
        name: str,
        arguments: list = None,
        documentation: str = None,
        tags: list = None,
        body: list = None,
        return_value: str = None,
    ) -> str:
        """Format a single keyword"""
        lines = [name]
        
        if arguments:
            args_str = '    '.join(f"${{{arg}}}" for arg in arguments)
            lines.append(f"    [Arguments]    {args_str}")
        
        if documentation:
            lines.append(f"    [Documentation]    {documentation}")
        
        if tags:
            lines.append(f"    [Tags]    {'    '.join(tags)}")
        
        if body:
            for line in body:
                lines.append(f"    {line}")
        
        if return_value:
            lines.append(f"    RETURN    {return_value}")
        
        return '\n'.join(lines)
    
    def _format_test_case(
        self,
        name: str,
        documentation: str = None,
        tags: list = None,
        setup: str = None,
        teardown: str = None,
        body: list = None,
    ) -> str:
        """Format a single test case"""
        lines = [name]
        
        if documentation:
            lines.append(f"    [Documentation]    {documentation}")
        
        if tags:
            lines.append(f"    [Tags]    {'    '.join(tags)}")
        
        if setup:
            lines.append(f"    [Setup]    {setup}")
        
        if body:
            for line in body:
                lines.append(f"    {line}")
        
        if teardown:
            lines.append(f"    [Teardown]    {teardown}")
        
        return '\n'.join(lines)
